apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-api
  name: svc-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector: 
    app: deployment-api
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3333