@host = http://localhost:3333
# @host = http://localhost:31100

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ0xJRU5UIiwic3ViIjoiZTlmZDhhZjItZGQzYi00ZDUwLThjODMtMDIxZjhlMGQ3OTkzIiwiaWF0IjoxNzEwODYyMzcwLCJleHAiOjE3MTA5NDg3NzB9.B8KdObtHjMTapDpGZRhOBjt6f-Igwu_9_MxqMk6wmRs

# @name get-orders
GET {{host}}/orders

###

# @name get-orders-queue
GET {{host}}/orders/queue

###

# @name get-order-by-id 
GET {{host}}/orders/1676f8da-6649-47c3-bab7-30a34477de7c

### 

# @name create-order
POST {{host}}/orders  
content-type: application/json
Authorization: Bearer {{token}}

{
  "paymentMethod": "QR_CODE",
  "paymentStatus": "PENDING_PAYMENT",
  "combos": [
    {
      "sandwichId": "062b0bb6-6a60-434b-a54f-5bfb109795d6",
      "drinkId": "16db4236-0b8f-4fb1-a020-1220a04f02f7",
      "sideId": "88e2ac98-2cd1-40b3-81d1-aaeec76ea807",
      "quantity": 2,
      "annotation": "remove the tomatos"
    }
  ]
}

### 


# @name update-order-status
PATCH {{host}}/orders/8c292d19-887d-4eb0-b987-d7f8b920d16a
content-type: application/json

{
  "status": "READY"
}

### 

# @name webhook
POST {{host}}/orders/webhook
content-type: application/json

{
  "resource": "https://api.mercadolibre.com/merchant_orders/15308297344",
  "topic": "merchant_order"
}


