
@host = http://localhost:3333
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiI0MmUyYTJjMi01ZTk2LTQxMGMtOWNhOS00ZDAyYzVjZGFmNTYiLCJpYXQiOjE3MTA4NzQyMjYsImV4cCI6MTcxMDk2MDYyNn0.oUY4OFZfJlu_CJFZprAvLRQqwtRmCOWL_o_vJnqQv8s

@tokenClient = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ0xJRU5UIiwic3ViIjoiZTlmZDhhZjItZGQzYi00ZDUwLThjODMtMDIxZjhlMGQ3OTkzIiwiaWF0IjoxNzEwODczNzU0LCJleHAiOjE3MTA5NjAxNTR9.OhV2LF6jr8J9Hpyd93ZFcJCCNvYdAqRF6xnODU4GNlo

# @name get-products
GET {{host}}/products

### 

# @name get-product-by-id
GET {{host}}/products/0c3c1658-c9e5-42a0-b87b-3d9a7dfe07ac

### 

# @name create-product
POST {{host}}/products
content-type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "name": "Batata Rustica",
  "description": "Batata Rustica",
  "price": 0.2,
  "category": "SIDE_DISH"
}

### 

# @name edit-product
PUT {{host}}/products/0b612db0-d081-4df4-a564-28ac04cd1cfe
content-type: application/json

{
  "name": "hamburguer de costela 2",
  "price": 20,
  "description": "hamburguer de costela",
  "category": "DESSERT"
}

### 

# @name inactive-product
DELETE {{host}}/products/0b612db0-d081-4df4-a564-28ac04cd1cfe
content-type: application/json

